### ISSUE TITLE
Unable to open mailboxes

### ISSUE THREAD

**Issue by Kaelico** [Zerthick/Mailboxes#1]
Players are able to create a mailbox most of the time (Trying to figure out why it doesn't always work). Once the mailbox is created the recipient of the mail is unable to open the chest. If you spam right click fast enough you can catch a small glimpse of the chest UI before it vanishes. 

We were able to get the mail to drop after multiple attempts of breaking the mailbox as well. This results in the "package" being unable to place or open.

**Comment by Zerthick** [comment]
Hmmm, that's bizarre, what version of Sponge are you using? Also, when you go to open the mailbox the chest doesn't actually "open" it should just present the mail inventory, similarly, the mail inventory isn't actually stored in the chest since they are all linked, meaning breaking the chest should have no effect.

**Comment by Kaelico** [comment]
I apologize for not including the Sponge version. Wasn't thinking about that when I was reporting this ha ha. As for breaking the chest it was really weird, I'll be able to test it again tonight after I get off work. The mail inventory doesn't display either. All we can see is a small glimpse of some kind of UI which I assumed (and got wrong haha) was the chest UI.

EDIT: Pixelmon 5.0.1 is on the server as well. Not sure if that's relevant. 
Minecraft 1.10.2
Forge 12.18.3.2215
Sponge 5.1.0 Beta 2070
Mailboxes 0.2.0

**Comment by Kaelico** [comment]
Decided to get on while at work to get you the report faster. Restarted the server to re-enable Mailboxes and this error appeared on join.
EDIT: Currently unable to test Mailboxes at all since the errors started. I'll try resetting everything when I get a chance and try again.

Error: http://pastebin.com/BmM5vnJZ

Following error appears when placing a chest.
Error: http://pastebin.com/e6E53pdN

When opening a chest
Error: http://pastebin.com/QhfLLFrG

If needed I can create another issue regarding the errors above.

**Comment by Zerthick** [comment]
Hello! Sorry it took me so long to get back to you! I have been able to replicate the issue with regards to not being able to open mailboxes, what's strange is that this behavior only seems to occur on SpongeForge and not SpongeVanilla, I'm going to be running some further tests to see if I can figure out why.

**Comment by Zerthick** [comment]
Update: I've verified that this is indeed an issue with SpongeForge, I've notified the Sponge developers and they are working on a fix, until then it seems that unfortunately Mailboxes will be broken ☹️

**Comment by Zerthick** [comment]
Should be fixed with this commit: https://github.com/SpongePowered/SpongeForge/compare/d70db88593eb...cbfebcc48bac

Just have to wait for a new build of SpongeForge to come out!

**Comment by Zerthick** [comment]
So this is still an issue, I've reopened the issue [here](https://github.com/SpongePowered/SpongeForge/issues/1932) so hopefully the issue will be resolved then. In the meantime set the mailbox block to be something other than a chest.

**Comment by Zerthick** [comment]
Is this issue still occurring? The Sponge people have claimed to have fixed it.

**Comment by Zerthick** [comment]
This issue no longer occurs on the latest stable build of SpongeForge 1.12.2-2705-7.1.0-BETA-3206, marking this as resolved.
