### ISSUE TITLE
[Enhancement] Trapped chests

### ISSUE THREAD

**Issue by aWitch-Doctor** [Zerthick/Mailboxes#2]
Can you add in the ability to use trapped chest for mail boxes as well?

**Comment by Zerthick** [comment]
Better, I'll let you configure it to any list of blocks you want! :smile:

**Comment by aWitch-Doctor** [comment]
Lol that works even better... hmm I'm getting a command block for mine. Perks of running a server

**Comment by Zerthick** [comment]
Added in [v0.4.0](https://github.com/Zerthick/Mailboxes/releases/tag/v0.4.0)! Delete the default config and let it regenerate to see where you can enter the ids, or take a look at [this](https://github.com/Zerthick/Mailboxes/blob/master/src/main/resources/assets/mailboxes/DefaultConfig.conf). :smile:
